### ISSUE TITLE
啊啊啊，有没有m.2接口的核心板PCB啊？跪求

### ISSUE THREAD

**Issue by chenpotatos** [MehverOSHWH/Transfer-QuarkN#3]
啊啊啊，有没有m.2接口的核心板PCB啊？跪求

**Comment by Culturenotes** [comment]
同求

**Comment by Mehver** [comment]
> 啊啊啊，有没有m.2接口的核心板PCB啊？跪求

才看到 (

https://github.com/PiCenter/QuarkNPi/issues/3

我印象里model-n只开源了基板。毕竟m2接口的核心板让Seeed矽递量产了，淘宝上还是要卖钱的嘛。不过也可能将来会开源吧。有基板的资料你也可以自己做核心板。
